name = "Webring du Nouveau Printemps"
domain = "ring.nouveauprintemps.org"
description = [
	"Le Webring du Nouveau Printemps est une ouverture sur un internet différent. Ici, tous cherchent à recentrer le numérique sur l'humain, tous critiquent la vision des GAFAM, tous rêvent d'un internet libre, respectant l'individualité de chaqu'un et n'oubliant pas la question écologique.", 
	"Nouveau Printemps est un collectif luttant contre le monde technologique des GAFAM et leur capitalisme de surveillance, leur censure et leur manipulation des masses. Nous proposons de nombreux services permettant de se libérer de leur emprise."
]
join_the_ring_path = "join_ring.html"
legal_information_path = "legal_information.html"
favicon_path = "logo.svg"
public_folder = "public"

[translation]
  random_website = "Aller sur un site aléatoire"
  internal_pages = "Pages internes :"
  home_page = "accueil"
  join_the_ring_page = "rejoindre le webring"
  legal_information_page = "mentions légales"

[[website]]
  name = "Nouveau Printemps"
  url = "https://nouveauprintemps.org/"
[[website]]
  name = "Anhgelus Morhtuuzh"
  url = "https://anhgelus.world/"
